Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

$form = New-Object System.Windows.Forms.Form
$form.Text = 'Print Driver Installer'
$form.Size = New-Object System.Drawing.Size(300,300)
$form.StartPosition = 'CenterScreen'
$iconBase64      = 'AAABAAEAMDAAAAEAIACoJQAAFgAAACgAAAAwAAAAYAAAAAEAIAAAAAAAACQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAAAEwAAAAgAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAVAAAAAxMHDUyGDBZkuSMjUJYaGDZtAwMaRwAABCgAAAATAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAAAAQMGP20OIpD2HDm9/5uXvf/DsbH7n5Cb7XlugtZUTWe1Mi5MjxQSMWYBARZBAAACJAAAABAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAREAAAAACgUQZLMPKqX/HjzD/7Suzv/WydT/08bU/+TS0v/l0cv/1sO//7yqrfmZi5fqc2l+0U9IZK8tKUiIDw4tYAAAETwAAAAgAAAADQAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABARUAAAAACwUSabkQK6b/Hz3E/7Stzv/MwdL/o6LS/5eZ0v+XmtL/paTT/7u11P/Sx9X/4tLT/+LQzf/SwcD+tqit95SIluZjXXbMFRlUqQYKP3EAABEVAQEeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABARUAAAAACwUSaLkQK6b/ID7F/7Wvzv//59L//eXS//bg0v/o1tL/1cjT/7631P+oqNT/m57V/5qe1f+mqNf/u7jY/9TK2v/Qw8T/Nkmt/xkupPQHC0hPDBN3AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABARUAAAAACwUSaLkRLKf/IT/H/7Otz//HvdL/vbbS/9TH0v/n1tP/9eHV//3o1///6tn/+ufa/+3e2//a0Nv/w7/b/7Ky2//DvMj/PVK5/yA6vvwKEFpeEh6YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABARUAAAAACwcTarkTLqn/IkDI/7Wvz//YytL/s67S/6Gi0/+XmtP/l5vU/6Gk1v+zstj/ycPa/97U3f/w49//++zh///x4//f087/PVO8/yI8v/wLEVpeEx6XAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABARUAAAAACwoWbLkWMaz/I0HK/7awz///5tL//ubT//3m1f/349b/69vY/9rP2v/Fwdv/sbLb/6Gn3P+aotz/naTc/66y3//JxM//QFa+/yQ+wvwLEVpeFB+YAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABARUAAAAACw0ZcLkaNbD/JELL/7Su0P++ttL/q6nS/8C51P/Uydf/5tja//Tk3f/97eD///Hk//7x5v/37ej/6ePo/9rX6P/QzNT/QljB/ydAxfwMElteFSGaAAAAAAAAAAAAAAAAAAAAAAEAAAACAAAAAAkGBwAQCgwBBQMEAQgFBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABARUAAAAACxEdc7kfOrX/JUPM/7ex0P/k09L/x77T/7Sx1f+kptb/mp/X/5ee2f+epNv/q7De/76/4v/S0Ob/5eDq//bv7//f2dr/RFrE/ylCx/wME1xeFiKbAAAAAAAAAAABCgkJICAgIF8lJSV0FRUVUQICAisSDww5Z1hKXWRVSD4iGhUbAAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABARUAAAAACxYid7klP7r/I0LN/52e0P/03tL/+uTU///p1///6tn/++nd//Lk3//k2+L/0s/j/7/C5P+uteT/oazk/6Gs5f/Dxdn/R13H/ytFyvwNE1xeFiCSAAAAAAMaGho9TU1NuHZ2dvR/gH/7aGho7VFOTNSQe2jT69bD8OjYyebRv63Er52MlYV1ZmNTRjo2FxEMFwAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABARUAAAAACxsmfLkqRb//I0HO/zVP0P9abNP/dIDW/46U2P+oqdr/wb7d/9fQ4P/o3+T/9uzo//717f//+fD///rz//z49v/e3N//SF7J/y5HzfwOFF5cAAAAAyMiIlBfX1/Qpqin/83Sz//S19X/yca//86ymf/23sr///jy///79v//+vX//PXt//Po3vbi08Xgyriou6qZiIuAcGBZRzsxLwsHBRIAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAABARUAAAAACyArgbkwSsT/JELP/yVE0f8iP8n/ITy+/yVCyv8rSNL/NFDY/z9a3v9PZ+L/Y3jl/3uM6f+Uoez/rrfw/8jO9f+4vd7/RF3S/zBJz/0LD0h5KyomZW1tbd+1t7b/1drX/9Xb2f7XzL3/576c/vvgyf7/8+j//vTr/v727/7/+fP///v2///9+v///vz///z4//z17v7y5tvz3tDC2sOyorKhkICBqZOAO//42AP01LgAAAAAAAAAAAABARUAAAAACyUwhbk2UMr/JEPP/ydG0/8dM6T/FSR+/xkqjP87SZf/eYKw/297t/9hcb//VWjH/0th0P9FXtj/Ql3f/0Ne5f9DX+j/Plvr/zNMz/8vMlDjenp47b/CwP/W29n/1NnW/tW9pP/ms4j/+9zD/v/s2///7d7//vDi/v/y5///9Ov//vbv/v/48v//+vb//vz5/v/+/P////7////+///79//y4M/81Lqikti7oQncwKYAAAAAAAAAAAABARUAAAAACyo1irk8Vc//JUPQ/yhG1P8dM6P/GSmG/xwukv9ZYpj/t7az/7i3tf+4uLb/uLi5/6WntP9sdKj/bHWs/3yGuf9MZd//P13w/zRM0P9QUm3/vcC8/9bc2f7V1c//1ayH/umvf/783MD//+XP/v7m0v7/6db//uva/v7t3v7/8OP//vLn/v706/7/9+///vjz/v769v7//fr//vr1/vrq2/+2q6D9SEZDdP///wAAAAAAAAAAAAAAAAABARUAAAAACy85jrlBWtT/JUTQ/yhH1P8eNKX/GiuI/x8xlv9aZJv/tra1/7m5uf+8vL3/wsPC/6Gkt/8/TLD/O0iy/3+Fsv9jd9r/QF7z/zhQ1P9PUm3/VFVT/nNsZf6whGH/0pxw/u/Ps/7628D//uDG/v/jy/7/5c///+fS/v/p1v7/69r//u3e/v7w4/7/8uf///Xr/v/38P787N7/8NnD/t7Zzv+0t7XzVVVVWP3+/QAAAAAAAAAAAAAAAAABARUAAAAACzM9krlGX9j/JkTR/ylH1P8fNKb/GyyK/yAymP9bZZ3/uLi3/7y8vP/AwMH/x8fG/6SnvP9EULf/Pku7/3yDt/9led3/QmD1/ztT1/94e5b/Zmdm/j8tIP9zV0H/k39u/qqSfv+/pY//0bae/uHFrf/v07v/+N3G/v7kzf//59P//+rX/v/r2v//7uD//u7f/vXXvf/ly7L/1tXN/7W5t+h7fHtxGBcXCTs6OgAAAAAAAAAAAAAAAAABARUAAAAACzdBlblLY9z/JkTR/ylH1f8fNab/HC2L/yIzmv9dZp//u7u6/8DAwP/ExcX/zMzM/6irwP9HVLv/Qk/A/3+Gu/9ne9//RGL3/zxU2P9/gp3/v8C+/qytrf6TlJT/fHp4/m1oZP5tY1r/eWte/o98bP6nkX7/vaWR/s+2ov7fx7L/7dXA/vjizv7838f/7cGc/t3Gr//O0c3/mZua3VRUU1MAAAADFxYWAAAAAAAAAAAAAAAAAAAAAAABARYAAAAACztFmrhTa+P/KEbT/ylI1v8eM6T/GiiD/x8vk/9dZp7/v7+//8TFxf/Jysv/0NHR/6uuw/9HU73/Q1DF/4GHvv9ofOD/RmT5/z5W2v+FiKP/ysvJ/sbHx/7Fxsb/wsPD/ru8vP6sra3/lpeX/n9+fP5uaWX/a2Jb/ndqXv6Me23/pJCA/rCSef6cclD/q5uL/ra6uP98fXz+Q0ND3icnJ34DAwMUCgoKAAAAAAAAAAAAAAAAAAAAAAABARcAAAAAAy82iIxUZMr2RlrL+kFXzf41SLH/KzmW/yw5kf9tcpj/v7+//8XGxv/MzM3/09PT/8LDzf92fbv/Zm+9/5qfw/9rf+T/RmT8/z1Tz/+ZnLH/0dLR/svMzP/Oz8//zc7O/snKyv/Gx8f/xcbG/sLExP+8vb3/rq+v/pmamv+CgYD/cGxo/lpJO/8tJiD/VVZX/lVUVf9DQkP/QkJD/0VFRe0oKChJWlpaAAAAAAAAAAAAAAAAAAAAAAAAAAAACgxTAAcIRREYHGM+IiZzTyQreWAmLoFwJS6GgTg+c6t0dYX5jo+c/4+QnP+Skp7/mZqk/6Skrf+mpq7/pqaw/5KVq/9EVbT/PlHC/32Dtv+6u73/c3Nz/mBfYP57e3v/m5yc/re4uP7Iycn/zs/P/svMzP7Iycn/xsfH/sXGxv7DxMT/vb6//rGzs/6ho6P/rKyt/pGakf5lfWP/XmVe/1NTU/k0NDVafn5+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAREREADMzMzqPkZLvvcLD/7a6vP6vs7b/v8LG/tLT2v/Ky9L/wcLL/6mrv/+lp77/wcLO/97f4P6Eg4P/SkdJ/kpISf5FQkT/Q0BC/khHSP5aWVr/lpaX/szNzf7Ky8v/ycrK/s/Q0P7Nzs7/ycrK/sbHx/7Fxsb/xMPF/pe5lf4vwyf/TclL/3qLefY2MzZUcHBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0NDEAQEBAAC4uLjKRlZTqys/O/8bLyv/L0M7/7vDv/vf4+P/3+Pf/9vf2/vX29f/09fT/8/Tz/tvb2/9ramv/V1VW/ldVVv9WU1X/VVJU/lJPUf9NSkz/R0VG/ltaW/9eXV7/Xl5e/oGBgf+nqKj/xcbG/tDR0f/Nzs7/y8zM/rjFuP92xnT/X9Jg/32SfPQ0MDRNX19fAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOTk4ACYmJiuOkZDjzdPS/8zS0P7h5OT/8/T0/vP09P709vb/9fb2/vX29v719vb/9/j4/ru7u/5lY2T/YmBh/mBfYP5fXV7/XVtc/ltaW/5aWFn/WFZY/lRRU/5SUFL/UE1P/klGSP5GREb/V1ZX/qipqf7X2Nj/1NXV/tLS0/7Rz9H/yc3K/5KUk/ErKytETExMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANTU1ACEhISWLj47e0NfV/9re3f7q6+v/7O3t/u7v7/7v8PD/8fLy/vLz8/709fX/6erq/ouLi/5ra2v/bGtr/mppav5paGj/Z2Zn/mVkZf5kYmP/YmFi/mFfYP5fXV//XVxd/lxaXP5bWVr/UlBS/mdmZ/7W19f/3d7e/trb2/7Y2dn/2NjY/5SUlOoiIiE4Ozs7AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAALCwsABcWFh6FiYjY1drY/9/h4f/j4+P/5OXl/ubn5//o6en/6uvr/uzt7f/u7+//tbW1/nV1df90dHT/c3Nz/nJycv9xcXH/cG9w/m9ub/9tbW3/bGts/mppav9paGn/Z2Zn/mZlZf9kY2T/YWBh/nh3eP/d3t7/5ebm/uPk5P/h4uL/3+Dg/5CQkOEYGBgsLy8vAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKikpABQTExZ3eXjJxsjI/9jZ2f/b3Nz/3N3e/t7f3/7g4eH/4uPj/ubn5/7Cw8P/enp6/nJxcf50c3P/dHR0/nV1df51dXX/dXV1/nV1df50dHT/dHN0/nNycv5ycXH/cHBw/m9ub/5ubW3/ampq/qampv7v8PD/7O3u/uvs7P7p6ur/4uLi/4GBgsYAAAAWGxsbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJSUlAAAAAAJQT09AeHh4ppmZmeGztLT7ycnJ/9TV1f7Z2tr/29zc/r29vf52dXb/aGZn/mppav5sa2v/bWxt/m9ubv5wcHD/cXFx/nJycv5zc3P/dHR0/nV1df51dXX/dXV1/nV1df50dHT/fXx9/tjY2P719vb/8/T0/vHy8v7x8vL/1dbW/2BgYJAAAAADBAQEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAmJiYADw8PBjk4OCRgYGB4h4eH9p2dnf+vsLD/nZ6f/mZlZ/9aWVr/Xl1e/mBfYP9iYWH/ZGJj/mVkZf9nZmb/aGdo/mppav9ramv/bWxt/m5ubv9vb2//cXBx/nJycv9xcXH/p6en/vLz8//19vb/9fb2/vX29v/3+Pj/tLW18jo5OUttbW0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHp7ewB2dnY2sbKy8NDR0v+vq6f/oZKE/op+dP5xamb/YF1c/lhWV/5WVVb/V1ZY/lpYWv5dW1z/Xl1e/mBfX/5iYGH/Y2Jj/mVkZf5mZWb/aGdo/mhnZ/59fX3/2NnZ/vDx8f7w8fH/8fLy/vT19f7n6Oj/gYGBugUFBRIoKCgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHh4eABzc3QWqqqpf7+nlN/jxKj//9u8/vvXt/7uzK//2Lui/rulkf6bi37/fnRt/mZhX/5ZV1f/VFNU/lRTVf5WVVf/WVdZ/ltZWv5dW1z/XVtc/m5tbv69vb7/5ufn/ufo6P7p6ur/6+zs/uvs7P+np6fpRkVFS6OjowAFBQUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC2WBYAr0oEE9KLVMr61rj//9/D/v/dwP//3L7//9y9/v/cvP/+2bn/99Oz/uTFqf/KsJn/q5eH/ol9c/9vaGT/Xlta/lZUVf9SUFH/Z2Zn/7W2tv/d3t7/3+Dg/+Dh4f/j5OT/4ODh/6qrq+5YWFhqAAAABBkZGQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADLez0AxGsqPuGofPH+5M7//uPM/v7hyf7/4Mb//t/D/v7dwf7/3L///9u9/v/bvP7/27v//9q5/vrWtf7uy67/2ryh/qmOeP+Jh4f/iIeI9ZOTk92jo6PrsrOz+cDBwf/Dw8P/mJiY4FRUVF8AAAAFGxsbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAKc8BQD///8Az4dTh+zEpf//69v//ujW/v7n0/7/5dD//uTN/v7iyv7/4cf//t/F/v7ewv7/3cD//tu+/v/bvP7/27v/+9Ku/ciihN+8vb7BlZaWWy8vLx5AQEAwU1NTT2RkZHFlZmV4RUVFNAAAAAIREREAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAkQAAAM+KUwDHd0It3KiB3fbgzv//8eT//u7g/v/s3f//69r//unX/v/o1P//5tH//uTP/v/jzP//4cn//uDG/v/fw///3sL/8MGb5rZyPzxYa3gNAAAAABkZGQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAvmIkALNHAgzapn+j6cet//317P//9e3//vTq/v7y5/7/8eT//u/i/v7t3/7/7Nz//urZ/v7p1v7/59P//uXQ/v/kzf794Mf/46t+q5MJAAe3UQoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC1TgAA////ANGRYW7kvqL59efb///8+f7/+vX//vnz/v738P7/9u7//vTr/v7z6f7/8eb//vDj/v7u4P7/7d3//uva/v/q2f/32L/604xXW+a1iwCsOwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC2TgAA////AMd3PV3nxaz0/v38/////v////7///78///8+f//+/f///n0/v/48v//9+///vXt/v/06v//8uf//vHl/v7v4v/qwaHOulcRGcBlJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAyXtDAMNvMjDeroue6Meuv+zRvdnx3c7r9ejd9/nw6f789/L//fr3//78+f///Pn///z3///69f//+PL///fw//fl1vzXmm1t////AKgzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAJcBAABmAAACoygAC7pZFBrGdTovzopYSdaccmfdrIiH47udpejIr8Lt1MDa8d7O7Pbn3Pj57+b++vDn/+W9n7i3Ug4UwGcpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAD/KAAAaQAAA6cwAA28XxocyHpAMtCPXkrYoXdp3KmDf8l/SyrjsX0AawkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD///////8AAOH//////wAAwB//////AACAAP////8AAIAAB////wAAgAAD////AACAAAP///8AAIAAA////wAAgAAD////AACAAAP///8AAIAAA8z//wAAgAADAB//AACAAAIAAf8AAIAAAAAAHwAAgAAAAAAHAACAAAAAAAcAAIAAAAAADwAAgAAAAAAPAACAAAAAAA8AAIAAAAAAHwAAgAAAAAAfAACAAAAAAB8AAMAAAAAAHwAA/wAAAAAfAAD/AAAAAB8AAP8AAAAAHwAA/wAAAAAfAAD/AAAAAB8AAP8AAAAAHwAA/wAAAAAfAAD/wAAAAD8AAP/wAAAAPwAA//AAAAB/AAD/+AAAAH8AAP/4AAAA/wAA//gAAAH/AAD/8AAB//8AAP/gAAP//wAA/+AAB///AAD/4AAH//8AAP/gAA///wAA//AAD///AAD//+Af//8AAP///////wAA////////AAD///////8AAP///////wAA////////AAA='
$iconBytes       = [Convert]::FromBase64String($iconBase64)
$stream          = New-Object IO.MemoryStream($iconBytes, 0, $iconBytes.Length)
$stream.Write($iconBytes, 0, $iconBytes.Length);
$iconImage       = [System.Drawing.Image]::FromStream($stream, $true)
$Form.Icon       = [System.Drawing.Icon]::FromHandle((New-Object System.Drawing.Bitmap -Argument $stream).GetHIcon())

$OKButton = New-Object System.Windows.Forms.Button
$OKButton.Location = New-Object System.Drawing.Point(75,210)
$OKButton.Size = New-Object System.Drawing.Size(75,23)
$OKButton.Text = 'OK'
$OKButton.DialogResult = [System.Windows.Forms.DialogResult]::OK
$OKButton.Enabled = $False
$form.AcceptButton = $OKButton
$form.Controls.Add($OKButton)


$CancelButton = New-Object System.Windows.Forms.Button
$CancelButton.Location = New-Object System.Drawing.Point(150,210)
$CancelButton.Size = New-Object System.Drawing.Size(75,23)
$CancelButton.Text = 'Cancel'
$CancelButton.DialogResult = [System.Windows.Forms.DialogResult]::Cancel
$form.CancelButton = $CancelButton
$form.Controls.Add($CancelButton)

$label = New-Object System.Windows.Forms.Label
$label.Location = New-Object System.Drawing.Point(10,20)
$label.Size = New-Object System.Drawing.Size(280,20)
$label.Text = 'Please select your printer model:'
$form.Controls.Add($label)

$listBox = New-Object System.Windows.Forms.ListBox
$listBox.Location = New-Object System.Drawing.Point(10,40)
$listBox.Size = New-Object System.Drawing.Size(260,20)
$listBox.Height = 150
$listBox.add_SelectedIndexChanged({$OKButton.Enabled = $true})


[void] $listBox.Items.Add('DCP-7060D')
[void] $listBox.Items.Add('HL-1110')
[void] $listBox.Items.Add('HL-2130')
[void] $listBox.Items.Add('HL-2132')
[void] $listBox.Items.Add('HL-2140')
[void] $listBox.Items.Add('HL-L2300')
[void] $listBox.Items.Add('HL-L2340DW')
[void] $listBox.Items.Add('HL-L2365DW')
[void] $listBox.Items.Add('MFC-L2700DW')
[void] $listBox.Items.Add('MFC-L2710DW')



$form.Controls.Add($listBox)

$result = $form.ShowDialog()

if ($result -eq [System.Windows.Forms.DialogResult]::OK) {

$x = $listBox.SelectedItem.ToString()

$wshell = New-Object -ComObject Wscript.Shell
$success = $wshell.Popup("Printer has been installed successfully!",0,"Done")

$DCP7060D = "\\hopecc.sa.edu.au\source\SCCM\Applications\Printer Drivers\DCP-7060D\dpinst.exe"
$HL1110 = "\\hopecc.sa.edu.au\source\SCCM\Applications\Printer Drivers\HL-1110\dpinstx64.exe"
$HL2130 = "\\hopecc.sa.edu.au\source\SCCM\Applications\Printer Drivers\HL-2130\dpinst.exe"
$HL2132 = "\\hopecc.sa.edu.au\source\SCCM\Applications\Printer Drivers\HL-2132\dpinst.exe"
$HLL2300D = "\\hopecc.sa.edu.au\source\SCCM\Applications\Printer Drivers\HL-L2300D\dpinstx64.exe"
$HLL2340DW = "\\hopecc.sa.edu.au\source\SCCM\Applications\Printer Drivers\HL-L2340DW\dpinstx64.exe"
$HLL2365DW = "\\hopecc.sa.edu.au\source\SCCM\Applications\Printer Drivers\HL-L2340DW\dpinstx64.exe"
$MFCL2700DW = "\\hopecc.sa.edu.au\source\SCCM\Applications\Printer Drivers\MFC-L2700DW\dpinstx64.exe"
$MFCL2710DW = "\\hopecc.sa.edu.au\source\SCCM\Applications\Printer Drivers\MFC-L2710DW\dpinstx64.exe"


if ($x -eq "DCP-7060D") 

{ Start-Process $DCP7060D 
  Start-Sleep 5
    $success
 }

elseif ($x -eq "HL-1110") 

{ Start-Process $HL1110 
  Start-Sleep 5
    $success
 }

 elseif ($x -eq "HL-2130") 

{ Start-Process $HL2130 
  Start-Sleep 5
    $success
 }

elseif ($x -eq "HL-2132") 

{ Start-Process $HL2132 
  Start-Sleep 5
    $success
 }

elseif ($x -eq "HL-2140") 

{ PNPUtil.exe /add-driver "\\hopecc.sa.edu.au\source\SCCM\Applications\Printer Drivers\HL-2140\BROHLA7A.INF" /install 
  Start-Sleep 5
    $success
 }

elseif ($x -eq "HL-L2300") 

{ Start-Process $HLL2300 
  Start-Sleep 5
    $success
 }

elseif ($x -eq "HL-L2340DW") 

{ Start-Process $HLL2340DW 
  Start-Sleep 5
    $success
 }

elseif ($x -eq "HL-L2365DW") 

{ Start-Process $HLL2365DW 
  Start-Sleep 5
    $success
 }

elseif ($x -eq "MFC-L2700DW") 

{ Start-Process $MFCL2700DW 
  Start-Sleep 5
    $success
 }

elseif ($x -eq "MFC-L2710DW") 

{ Start-Process $MFCL2710DW 
  Start-Sleep 5
    $success
 } 
 
 }



